#=============================================================
#	Mike Mayr (MMayr15), Chalie Crow (LevenBravo)
#	Team 21
#	https://github.com/CSE220Team21/Lab5
#	MakeFile
#=============================================================

all: CrossReference clean

CrossReference: main.o Print.o Scanner.o Token.o bTree.o LinkedList.o
	g++ main.o Print.o Scanner.o Token.o bTree.o LinkedList.o -o CrossReference


main.o: main.cpp
	g++ -c main.cpp

Print.o: Print.cpp
	g++ -c Print.cpp

Scanner.o: Scanner.cpp
	g++ -c Scanner.cpp

Token.o: Token.cpp
	g++ -c Token.cpp

IdentifierBinaryTree.o: IdentifierBinaryTree.cpp
	g++ -c IdentifierBinaryTree.cpp

LineNumberList.o: LineNumberList.cpp
	g++ -c LineNumberList.cpp

clean:
	rm -rf *.o
