/*==============================================================*/
/*	Mike Mayr (MMayr15), Chalie Crow (LevenBravo)		*/
/*	Team 21							*/
/*	https://github.com/CSE220Team21/Lab5			*/
/*	MakeFile						*/
/*==============================================================*/

all: CrossReference clean

CrossReference: main.o Identifier.o IdentifierBinaryTree.o LineNumberList.o Print.o Scanner.o Token.o
		g++ main.o Identifier.o IdentifierBinaryTree.o LineNumberList.o Print.o Scanner.o Token.o -o CrossReference

main.o: main.cpp
	g++ -c main.cpp

Identifier.o: Identifier.cpp
	g++ -c Identifier.cpp

IdentifierBinaryTree.o: IdentifierBinaryTree.cpp
	g++ -c IdentifierBinaryTree.cpp

LineNumberList.o: LineNumberList.cpp
	g++ -c LineNumberList.cpp

Print.o: Print.cpp
	g++ -c Print.cpp

Scanner.o: Scanner.cpp
	g++ -c Scanner.cpp

Token.o: Token.cpp
	g++ -c Token.cpp

clean:
	rm -rf *.o
